/**
 * Liste des devises du monde (codes ISO 4217) proposées lors de la création
 * d'un compte et dans les paramètres de l'organisation. Chaque organisation
 * choisit la sienne ; tous les montants de l'application sont ensuite formatés
 * dans cette devise (voir formatMoney dans lib/utils.ts).
 */
export interface CurrencyOption {
  code: string;
  label: string;
}

export const CURRENCIES: CurrencyOption[] = [
  { code: "XOF", label: "XOF — Franc CFA (UEMOA)" },
  { code: "XAF", label: "XAF — Franc CFA (CEMAC)" },
  { code: "EUR", label: "EUR — Euro" },
  { code: "USD", label: "USD — Dollar américain" },
  { code: "GBP", label: "GBP — Livre sterling" },
  { code: "MAD", label: "MAD — Dirham marocain" },
  { code: "DZD", label: "DZD — Dinar algérien" },
  { code: "TND", label: "TND — Dinar tunisien" },
  { code: "EGP", label: "EGP — Livre égyptienne" },
  { code: "LYD", label: "LYD — Dinar libyen" },
  { code: "MRU", label: "MRU — Ouguiya mauritanienne" },
  { code: "GNF", label: "GNF — Franc guinéen" },
  { code: "GMD", label: "GMD — Dalasi gambien" },
  { code: "SLL", label: "SLL — Leone sierra-léonais" },
  { code: "LRD", label: "LRD — Dollar libérien" },
  { code: "CVE", label: "CVE — Escudo cap-verdien" },
  { code: "GHS", label: "GHS — Cedi ghanéen" },
  { code: "NGN", label: "NGN — Naira nigérian" },
  { code: "XPF", label: "XPF — Franc CFP" },
  { code: "CDF", label: "CDF — Franc congolais" },
  { code: "AOA", label: "AOA — Kwanza angolais" },
  { code: "ZAR", label: "ZAR — Rand sud-africain" },
  { code: "NAD", label: "NAD — Dollar namibien" },
  { code: "BWP", label: "BWP — Pula botswanais" },
  { code: "ZMW", label: "ZMW — Kwacha zambien" },
  { code: "MWK", label: "MWK — Kwacha malawite" },
  { code: "MZN", label: "MZN — Metical mozambicain" },
  { code: "TZS", label: "TZS — Shilling tanzanien" },
  { code: "KES", label: "KES — Shilling kényan" },
  { code: "UGX", label: "UGX — Shilling ougandais" },
  { code: "RWF", label: "RWF — Franc rwandais" },
  { code: "BIF", label: "BIF — Franc burundais" },
  { code: "ETB", label: "ETB — Birr éthiopien" },
  { code: "DJF", label: "DJF — Franc djiboutien" },
  { code: "SOS", label: "SOS — Shilling somalien" },
  { code: "SDG", label: "SDG — Livre soudanaise" },
  { code: "SSP", label: "SSP — Livre sud-soudanaise" },
  { code: "SCR", label: "SCR — Roupie seychelloise" },
  { code: "MUR", label: "MUR — Roupie mauricienne" },
  { code: "MGA", label: "MGA — Ariary malgache" },
  { code: "KMF", label: "KMF — Franc comorien" },
  { code: "SZL", label: "SZL — Lilangeni swazi" },
  { code: "LSL", label: "LSL — Loti lesothan" },
  { code: "STN", label: "STN — Dobra santoméen" },
  { code: "CAD", label: "CAD — Dollar canadien" },
  { code: "MXN", label: "MXN — Peso mexicain" },
  { code: "BRL", label: "BRL — Real brésilien" },
  { code: "ARS", label: "ARS — Peso argentin" },
  { code: "CLP", label: "CLP — Peso chilien" },
  { code: "COP", label: "COP — Peso colombien" },
  { code: "PEN", label: "PEN — Sol péruvien" },
  { code: "UYU", label: "UYU — Peso uruguayen" },
  { code: "BOB", label: "BOB — Boliviano" },
  { code: "PYG", label: "PYG — Guarani paraguayen" },
  { code: "VES", label: "VES — Bolivar vénézuélien" },
  { code: "GTQ", label: "GTQ — Quetzal guatémaltèque" },
  { code: "HNL", label: "HNL — Lempira hondurien" },
  { code: "NIO", label: "NIO — Cordoba nicaraguayen" },
  { code: "CRC", label: "CRC — Colon costaricain" },
  { code: "PAB", label: "PAB — Balboa panaméen" },
  { code: "DOP", label: "DOP — Peso dominicain" },
  { code: "JMD", label: "JMD — Dollar jamaïcain" },
  { code: "TTD", label: "TTD — Dollar de Trinité-et-Tobago" },
  { code: "BSD", label: "BSD — Dollar bahaméen" },
  { code: "BBD", label: "BBD — Dollar barbadien" },
  { code: "XCD", label: "XCD — Dollar des Caraïbes orientales" },
  { code: "HTG", label: "HTG — Gourde haïtienne" },
  { code: "CUP", label: "CUP — Peso cubain" },
  { code: "CHF", label: "CHF — Franc suisse" },
  { code: "NOK", label: "NOK — Couronne norvégienne" },
  { code: "SEK", label: "SEK — Couronne suédoise" },
  { code: "DKK", label: "DKK — Couronne danoise" },
  { code: "ISK", label: "ISK — Couronne islandaise" },
  { code: "PLN", label: "PLN — Zloty polonais" },
  { code: "CZK", label: "CZK — Couronne tchèque" },
  { code: "HUF", label: "HUF — Forint hongrois" },
  { code: "RON", label: "RON — Leu roumain" },
  { code: "BGN", label: "BGN — Lev bulgare" },
  { code: "HRK", label: "HRK — Kuna croate" },
  { code: "RSD", label: "RSD — Dinar serbe" },
  { code: "ALL", label: "ALL — Lek albanais" },
  { code: "MKD", label: "MKD — Denar macédonien" },
  { code: "BAM", label: "BAM — Mark convertible" },
  { code: "MDL", label: "MDL — Leu moldave" },
  { code: "UAH", label: "UAH — Hryvnia ukrainienne" },
  { code: "BYN", label: "BYN — Rouble biélorusse" },
  { code: "RUB", label: "RUB — Rouble russe" },
  { code: "GEL", label: "GEL — Lari géorgien" },
  { code: "AMD", label: "AMD — Dram arménien" },
  { code: "AZN", label: "AZN — Manat azerbaïdjanais" },
  { code: "TRY", label: "TRY — Livre turque" },
  { code: "ILS", label: "ILS — Shekel israélien" },
  { code: "JOD", label: "JOD — Dinar jordanien" },
  { code: "LBP", label: "LBP — Livre libanaise" },
  { code: "SYP", label: "SYP — Livre syrienne" },
  { code: "IQD", label: "IQD — Dinar irakien" },
  { code: "IRR", label: "IRR — Rial iranien" },
  { code: "SAR", label: "SAR — Riyal saoudien" },
  { code: "AED", label: "AED — Dirham des Émirats arabes unis" },
  { code: "QAR", label: "QAR — Riyal qatari" },
  { code: "KWD", label: "KWD — Dinar koweïtien" },
  { code: "BHD", label: "BHD — Dinar bahreïni" },
  { code: "OMR", label: "OMR — Rial omanais" },
  { code: "YER", label: "YER — Rial yéménite" },
  { code: "AFN", label: "AFN — Afghani" },
  { code: "PKR", label: "PKR — Roupie pakistanaise" },
  { code: "INR", label: "INR — Roupie indienne" },
  { code: "NPR", label: "NPR — Roupie népalaise" },
  { code: "BDT", label: "BDT — Taka bangladais" },
  { code: "LKR", label: "LKR — Roupie srilankaise" },
  { code: "BTN", label: "BTN — Ngultrum bhoutanais" },
  { code: "MVR", label: "MVR — Rufiyaa maldivienne" },
  { code: "MMK", label: "MMK — Kyat birman" },
  { code: "THB", label: "THB — Baht thaïlandais" },
  { code: "LAK", label: "LAK — Kip laotien" },
  { code: "KHR", label: "KHR — Riel cambodgien" },
  { code: "VND", label: "VND — Dong vietnamien" },
  { code: "MYR", label: "MYR — Ringgit malaisien" },
  { code: "SGD", label: "SGD — Dollar de Singapour" },
  { code: "IDR", label: "IDR — Roupie indonésienne" },
  { code: "PHP", label: "PHP — Peso philippin" },
  { code: "BND", label: "BND — Dollar brunéien" },
  { code: "MNT", label: "MNT — Tugrik mongol" },
  { code: "KZT", label: "KZT — Tenge kazakh" },
  { code: "UZS", label: "UZS — Sum ouzbek" },
  { code: "TJS", label: "TJS — Somoni tadjik" },
  { code: "TMT", label: "TMT — Manat turkmène" },
  { code: "KGS", label: "KGS — Som kirghize" },
  { code: "CNY", label: "CNY — Yuan chinois" },
  { code: "HKD", label: "HKD — Dollar de Hong Kong" },
  { code: "MOP", label: "MOP — Pataca macanaise" },
  { code: "TWD", label: "TWD — Dollar taïwanais" },
  { code: "JPY", label: "JPY — Yen japonais" },
  { code: "KRW", label: "KRW — Won sud-coréen" },
  { code: "KPW", label: "KPW — Won nord-coréen" },
  { code: "AUD", label: "AUD — Dollar australien" },
  { code: "NZD", label: "NZD — Dollar néo-zélandais" },
  { code: "FJD", label: "FJD — Dollar fidjien" },
  { code: "PGK", label: "PGK — Kina papou-néo-guinéen" },
  { code: "SBD", label: "SBD — Dollar des îles Salomon" },
  { code: "VUV", label: "VUV — Vatu vanuatais" },
  { code: "WST", label: "WST — Tala samoan" },
  { code: "TOP", label: "TOP — Pa'anga tongan" },
];

export const DEFAULT_CURRENCY = "XOF";

export function getCurrencyLabel(code: string): string {
  return CURRENCIES.find((c) => c.code === code)?.label ?? code;
}
